:PROPERTIES:
:ID:       99de5040-7b83-4433-850a-6db2d16a629b
:mtime:    20210701200901
:ctime:    20201221125304
:END:
#+title: Transitions from continuity to the discrete are not possible
#+FILETAGS: thesis vagueness continuity

* Context
The one recurring theme in my research interests seems to be that reasoning with, arguing over, and utilizing "discrete" concepts which are ultimately defined in a ()presumably) continuous spacetime always leads to either a contradiction or confusion about what is being argued about. Examples I encountered include:
+ the distinction between science and psuedoscience (Popper, Kuhn)
+ the distinction between observables and unobservables (van Fraassen, ...)
+ naming "the meter" (Wittgenstein, Kripke)
+ measuring a "real number" in a physics experiment
+ computing, producing a digital output from a continuous system
+ ...

Also useful to keep in mind: this idea is "essentially" an argument against essentialism. This is a useful keyword to search for.
* Thought

In my view, human reasoning consists of two conflicting tendencies:
1. We wish to reason deductively and grab onto discrete, somewhat abstract propositions which we can assign truth values
2. We wish to see "the real world", specifically spacetime, as continuous, in the sense that we believe it is infinitely divisible, without gaps.
   - My hunch is that the fact that spacetime is continuous lies behind this, but the conflict might also come forth from a more general, unavoidable vagueness of concepts, see [[id:3a80df2a-77b4-4626-a9fe-933257549a07][Continuity vs. Vagueness]]
     + Sub-hunch: the vagueness argument is more about justifying the naming of n F's as G and naming n+1 F's as H, while the continuity argument is stonger and prevents one from chopping up things into categories at all.

These are in conflict. A good way to illustrate this is analyzing the concept of a "human". Is it possible over all of time and space to pick out those and only those things that are humans? I don't think this is possible for many reasons:
a. Concept-wise, it is difficult to say what are humans and what are non-humans. We have two concrete cases of what are humans and what are not: associate professor Dr. Liam Bright is definitely a human, but a goldfish is definitely not. However, when exactly was the first human was born? There is a somewhat continuous line from me to a far away ancestor which we would not label human. Unless we somewhat arbitrarily draw a line, say, 2 million years ago, we cannot really pick out all the nonhumans from the humans this way.
   + This is more related to the vagueness argument than the continuity argument, although I feel like they are the same, I should come up with a more general word for this.
     - TODO come up with a better word for this
b. Time-wise, it is difficult to say when even an individual human "starts". We have to concrete cases of when a human exists and when not: when a person is 30 years old they are definitely human that exists, but before their parents were born they definitely did not exist yet. While I myself am not in favor of arguing that life starts at conception, it seems like the only natural starting point for what constitutes an individual human, otherwise you'd have to argue for "X" number of cells starts to make a human, again speaking ontologically. However, even if we decide to be hardcore bible-thumpers and claim that life starts at "conception", when is that? Is it when the sperm touches the egg-cell? But when IS that? Since time and space are continuous, there are an uncountable number of instants in where the sperm touches the egg for the first time: there is no "first touch". One might be inclined to specify are period of time instead, but, as I will argue later, this is just kicking the can down the road, as the process of going from non-human to human is now just ignored over this small time interval.
c. Space-wise, it is difficult to say where exactly a human phyiscally "ends". We have to concrete cases of where a human exists and when not: the center of a living human's brain is definitely part of them, but the center of the sun is definitely not. However, where EXACTLY does a human begin and end? A natural guess it at the end of their epidermis. Their epidermis is made up of molecules, and the last "epidermis" molecule is where the human ends. Even barring humans shedding skin and replacing their cells, the epidermis molecules is not a precise enough end. Molecules are made up of atoms, which consist of electrons and a core. We know that their relation is not as one of a sun and its planets, instead electrons are more akin to a cloud surrounding the core (which in itself is not so definitely positioned). This "cloud", however, extends as far space itself! Surely, the probability of finding the electron further than 1mm from the nucleus is already astronomically low, but it is non-zero. Where does one create the cut-off point? Even if one picks their favorite interpretation of QM where everything might have a definite position, then still the fact that space is continuous prevents us from creating a definite cutoff point
   - Kind of weak near the end, specifiy further.

I claim that it is not possible to assign ontological status to both. In order to reason soundly, then, we must do either one of the following
1. Give up the idea that spacetime is fundamentally continuous. This means that there are discrete units of space and time, which we could then group and give meaning to. For instance, a human could be defined as starting to exist at conception, which would be a definite instance in time and space.
2. Give up on the idea of ontological discrete groupings/concepts. Ontologically, there is no such thing as a human. While many might be willing to bite that particular bullet, this has far reaching consequences. Almost nothing would be justifiably ontologically real, except those things that could be mapped to the continuum of spacetime and exists on the same "level" as it. Basically, we can reason, but all our categories would be fundamentally arbitrary. This does not mean they are not useful, but that they cannot be part of the ontological furniture of the world.
(3. Reason "continuously". If we were somehow able to reason just using continuous arguments, this might work. However, I don't know what this looks like.)

* Refs
This topic is deeply related to a breadth of other topics. I try to explicate that in [[file:20201221144612-approaches_to_the_continuous_discrete_transition.org][Approaches to the continuous-discrete transition]]

* TODO Make a good distinction between the "continuity" and "vagueness" argument
