:PROPERTIES:
:ID:       e91108cb-a755-4ffa-861d-b228b26f441e
:mtime:    20210701195633
:ctime:    20201221144612
:END:
#+title: Relevant papers for discrete continuous transitio
#+FILETAGS: essentialism vagueness thesis continuity

* Context

    I am not the first person to have thought of this "problem" of reasoning about discrete entities against a continuous background, although I am one of the few to put it into those words.
    This meta-note is intended to create the start of an overview of how this problem has been talked about/tackled in the past/contemporary discussions. For instance, discussions surrounding essentialism have been around since Plato and are very closely connected to the topic at hand. Even though my thesis will not per se be an argument against essentialism, I should look at how this topic is tackled in order to
   a) regain my enthousiasm for my thesis. My passion against essentialism transcends my distaste of Platonism and is what I actually want to tackle. Just talking about Platonism is too abstract, I need easier examples
   b) find additional routes to tackle this topic. If this has either been done before very satisfactorily or in a way similar to my goals, it makes no sense at all try and construct myself out of this hole. Good philosophers think of things themselves, great philosophers let others do the thinking for them.
 c) know what not to do and which side-tracks to avoid. Although I do not think I will encounter the former that much, as I do not believe there is a strong pro essentialism argument, I do think that it is very easy to get lost in theories of naming etc., which I know will just end with me not doing anything useful.


* Body

First just start with putting some papers here with descriptions, tags, and related papers. See it as a scratchpad for things that will eventually become notes on their own, but for now it is useful to keep them in one file.
do not make the classification just yet.
Also try to just put either extremely relevant papers here or highly influential ones (100+ cites, although depends on field). If some rando with 5 citations makes a mildly relevant point it's probably not worth putting here.
Try to keep the tags specific to the paper. If a paper discusses biological species, don't put "metaphysics" as a tag unless it very specifcally discusse
*** [#B] Sober's "Evolution, Population Thinking, and Essentialism" cite:Sober1980
**** Tags
***** biology
***** species
***** "pro"-essentialism
***** specific

**** Summary/Why is it useful
            Sober discusses essentialism in biology, specifically about species, and argues against the view that Darwinian Evolution destroys essentialism, something which I also claim sometimes.
            However, he defines essentialism in a particular way, and then shows that while this version of essentialism IS undone by it, if we define essentialism (about species) differently, we see it can still work.

            He also talks about line drawing being a problem a lot, so it might be worth checking out.

            I don't know how he defines essentialsm again, but to me it sounds like his essentialism is essentialism in name only, and does not capture the essence of what I feel essentialism "

**** Strongly related papers (rebuttals/defences/continuations etc., keep same structure as above) :


*** Ian Hacking's "A Tradition of Natural Kinds" cite:Hacking1991

**** Tags (only include those things that are very explicit in this paper, it's not worth including things like "metaphysics" if it's a paper about biology, unless it specifically discusses metaphysical theories)
***** natural kinds
***** general
***** against essentialism

**** Summary/Why it is useful
            Hacking wishes to argue against a certain conception of natural kinds, that claims there "is a unique best taxonomy in terms of natural kinds, that respresents nature as it is, and reflects the netwoek of causal laws"
            He does not reject it on relativist, subjectivst or social construcionalist grounds, but because it does not make sense. Furthermore, this conception is quite new, the older one is a lot more modest, namely only including those things that are
            a) defined by a set of necessary and sufficient properties (at least on an IDEALIZATION) such that
            b) the possession f trhese properties is indicative of a very large number of other methodologically interesting properties and such that
            c) these defining properties are natural rather than socila properties

            This paper might be useful depending on how strongly I can link natural kinds to my "discrete categories". Maybe they are the same. In any case, this paper is quite general, which is nice.

**** Strongly related papers

***** Richard Boyd, 1991: "Realism, Anti-Foundationalism and the enthusiasm for natural kinds." cite:Boyd1991
****** Tags
******* natural kinds
******* pro-essentialism
******* general
******* explanation
****** Summary/Why it's useful
                Argue against Hacking that many property-cluster kinds and social-kinds "similarly" to natural kinds (on the model, whatever that means). He argues that these kinds, when important for EXPLANATION or induction, have certain properties which are also necessary properties of natural kinds, and should therefore be treated similarly. These properties are
                1. These kinds are defined a posteriori rather than socially "invented". There is phenomenon happening which we later give a name to, like gender. Gender in the abstract was introduced way later than gender norms.
                2. The way we use these kinds in explanation or inductions requres that it be defined "by a cluster of properties whose membership is determined by the CAUSAL STRUCTURE of the world" and is therefore independent of our social conventions in that sense.
                3. The way the relationship between the kind and the term that refers to it is established does not depend on our conventions but on the "existence of an epistemically relevant pattern of causal relations between instantiations of the kind and the term in question"

                Sooo Boyd does argue in favor a broader definition of natural kinds, and possibly for there existence? He takes causation to be quite important which is always a risky move to make, but might work out for him.

                His appeal to the explanatory power of the candidate natural kinds is very similar (probably even the same) kind of appeal Platonists make to the indispensability argument. This makes it interesting to look at.

****** Strongly related papers

*** Russel Duvernoy, 2015: "'Concepts' and Continuity: Onto-Epistemology in William James cite:Duvernoy2015
**** Tags
***** psychology
***** conflict
*****

**** Summary/Why it's useful

This paper analyzes the work of William James, specifically the conflict between Jaynes' idea that concepts are discrete entities and that conciousness is a continuous stream. It therefore very directly pertains to the conflict between discrete and continuous things, which is exactly what I'm interested in.

Unfortunately I don't think it goes into a lot of philosophically rigorous detail, but does at the very least mention or argue that there is a conflict here. Furthermore, it might be worth looking more into James.

**** Strongly related papers
***** William James, 1916 "Some Problems of Philosophy"cite:James1916
****** Tags
******* metaphilosophy
******* psychology
******* against essentialism?

****** Summary/Why it's useful

James (I believe) discusses precisely the conflict between continuous and discrete things, or at least points out that continuity is difficult and important.

****** Strongly related papers

*** Boundaries SEP

cite:Varzi2015
