:PROPERTIES:
:ID:       3dad96b9-a6bf-449f-981e-4e141f865dd5
:END:
#+title: Berry Connection
#+filetags: definition physics FQHE

* Berry Connection

\begin{align}
    \mathcal{A}_{\eta_i} =& -\frac{i}{2m}\sum_{j\neq i} \frac{1}{\eta_i-\eta_j}+\frac{i\bar{\eta}_i}{4ml_B^2}//
    \mathcal{A}_{\bar{\eta}_i} =& ++\frac{i}{2m}\sum_{j\neq i} \frac{1}{\bar{\eta}_i-\bar{\eta}_j}-+\frac{i\eta_i}{4ml_B^2}
    \label{eq:berryconnection}
\end{align}


* Backlinks :noexport:
** 3 linked references
*** [[file:20210327153604-the_configuration_space_approach_explains_the_possibility_of_anyons_not_their_occurence.org][The configuration space approach explains the possibility of anyons, not their occurence]]
**** The configuration space approach to quantum statistics does not (aim) to explain /when/ anyons /will/ occur, just that they can/have to occur in two dimensions.
I was very confused about the role of the use of the [[file:20210218153716-configuration_space_framework_for_identical_particles.org][configuration space framework for identical particles]] for describing anyons/the quantum hall effect, as it felt superfluous when the /appearance/ of [[file:20210218152830-fractional_quantum_statistics.org][fractional quantum statistics]] in  [[file:20210219125155-the_fractional_quantum_hall_effect_fqhe.org][the Fractional quantum hall effect (FQHE)]] is justified/calculated using the [[file:20210312130104-berry_connection.org][Berry Connection]], which has no real clear tie to the configuration space framework.

*** [[file:20210319113940-fractional_statistics_can_only_be_calculated_using_adiabaticity.org][Fractional statistics can only be calculated using adiabaticity]]
**** Fractional statistics can only be calculated using the assumption of adiabaticity
[[file:20210316143612-fractional_quantum_statistics.org][Fractional Quantum Statistics]] that appear in the quantum hall effect are calculated with the [[file:20210312130104-berry_connection.org][Berry Connection]]  using the assumption of [[file:20210223171329-adiabatic_theorem_quantum.org][adiabatic theorem (quantum)]], which says that a things won't move out of the ground state if you move it very slowly.

*** [[file:20210312123300-quasi_things_have_charge_e_m.org][Quasi-things Have Charge e/m]]
**** Quasi-holes/particles carry charge e/m › Berry Connection
The above "proof" is rather shoddy. However, we can make a more educated guess by looking using the [[file:20210312130104-berry_connection.org][Berry Connection]]

** Unlinked references
[Show unlinked references]
