:PROPERTIES:
:ID:       37c25546-4135-4012-b414-7747d6cedb2a
:END:
#+title: Wavefunctions are waves and do wave things
#+filetags: duh waves quantum

* Quantum mechanical wavefunctions are functions... of waves!

This is such a dumb thing that I'm almost embarrassed to admit it, but it's easy to forget that wavefunctions are, in fact, waves, and the terms which describe them are related if not identical to the terms describing waves.

The biggest one is [[id:57213ae1-eff2-4442-b04b-84706076061f][Phase (quantum)]]. For a long time I thought of phase as this strange, esoteric quantum property, like spin, but actually it's similar if not the same as regular ol' wave phase: the offset of a wave wrt to the origin.

Two sine waves are the same (for all practical purposes) if they are shifted about the origin a bit (that's why it usually doesn't matter if you pick sine or cosine waves), and two wavefunctions are also physically the same even if they have a different phase.

The phase only gains importance once two wave(function)s are (linearly) combined, because then it leads to [[id:085d376c-0967-4f50-b369-87369033bcf0][Interference]].

However, this does not immediately explain how a system would gain a [[id:fd2450df-e046-4d9c-a350-2be198e7fd04][Holonomy]], which is like a generalization of a phase. Still, it's a good analogy to keep in mind.
