:PROPERTIES:
:ID: 481293d6-42ea-484a-975b-1cc5ba1708fa
:collapsed: true
:mtime:    20210711223538
:ctime:    20210210135331
:END:
#+title: Condition of adequacy for approximate instantiation
#+filetags: approximation

* Context

In cite:Shech2019, Shech proposes a "condition of adequacy" for something to count as an approximate instantiation in cite:Leng2012 's sense, see [[id:013d6de0-7da7-4894-be91-ef3705945daa][approximate instantiation as an argument against Platonism]]

It is very similar to my proposed distinction between problematic and unproblematic idealizations, see [[id:1fbefa5c-d5a1-4061-a043-e7c2ffd7c596][small sample on infinite vs normal idealization]]
* Body

Shech proposes that a nominalist scientific realist account of certain phenomena can only be justified if there the limit properties of the physical system match the properties of the limit system which is used to represent said system.

This condition then, only really applies to infinite idealizations, not to any reprentation, as those normally dont use limits.

In cite:Norton2012 's terminology: the condition of adequacy is coreferential with "promotable" idealizations.

I think this condition is much too strong: the distinction makes sense, but this does not at all straightforwardly lead to this conclusion, only if you assume Leng's "way out" of the indispensability argument ([[id:c45736b9-4f0e-43ef-a8e5-4dcfc632b9f8][enhanced indispensability argument (EIA)]] )to be the only way.
