#+title: idealizations should be distinguished by outcome, not by operation
#+roam_tags: claim thesis idealizations

* Context

When idealization is discussed by for instance [[file:Strevens 2007 - The Structure of Asymptotic Idealization.org][Strevens2019a: The structure of asymptotic idealization]] or cite:Norton2012 , I have difficulty knowing what they are exactly talking about, see [[file:20201218180308-confusing_approximations_and_idealizations.org][confusing approximations and idealizations]]. This note is an attempt to clarify what the problem is and how to tackle it.

* Body

The problem with Streven's, Norton's and perhaps Batterman's discussions about infinite idealizations or asymptotic idealizations, is that they distinguish infinite idealizations from other things, be that normal idealizations or approximations, by the operation by which they are achieved, BUT then discuss the merits or results of that operation, which then invariably introduces another distinction: between infinite idealizations which do not smoothly approach the limit, and everything else. The latter is generally seen to be unproblematic, at least in the sense that scientific representation or modelling is assumed to be unproblematic. The former is where the difficulties lie and where disagreement arises, at least in the context of the discussion on infinite idealizations. Few people would disagree with Norton by saying that approximations are something else, they disagree that all infinite idealizations can be explained away as approximations, namely those infinite idealizations that do not smoothly approach the limit.

I propose therefore that, in discussions about infinite idealizations, we distinguish first and formost between the following (nomenclature subject to revision):

** Disinction
*** Continuous operations
Non discontinuous operations, converging limits, non-problematic idealizations, approximations etc. all fall in this class. They are relatively unproblematic, in the sense that there is no major dispute about whether or not the ought to be used at all or whether they /are/ used in science. They include Norton's approximations and Streven's simple idealizations, but also Norton's converging infinite idealizations and Strevens' "non-interesting" asymptotic idealization.

*** Discontinuous operations
This is just the class of those infinite/asymptotic idealizations which do not smoothly approach the limit. I think this is the interesting class, and the one we should distinguish.

** Merit

The merit of this approach, I claim, is that we now both distinguish between the operation which arrives at these idealization as well as their result, and thus do not get bogged down with discussions or distractions about the "easily understood" idealizations belonging to the class of infinite idealizations. It just doesn't make sense to look at them like that.

** Disadvantage

a) This distinction doesn't say anything specific about WHAT is discontinuous, it matters a lot which property you're looking at I think
b) This distinction groups a lot of things together under "continuous", operations and concepts between which we can distinguish further. Approximations are not idealizations and it is useful to note the difference, but the problem with distinguishing only arises when (in this case) the promotion relation doesn't work. This failure of promotion is the interesting factor, not the conceptualization of an idealization as separate model. While this conceptualization is interesting to talk about, it is not what is at stake, and Norton's distinction has done some harm in this regard.
