:PROPERTIES:
:ID:       2d54ce7d-5106-4873-a439-5a50edff1156
:END:
#+title: Test Driven Writing
#+filetags: :writing:thesis:idea:

I really like the idea of [[id:c25b8934-ddf3-47e1-b5ec-aa959858df2d][Test Driven Development]].
One of the reasons I usually struggle with writing is that it is hard to see whether I am making any progress, and whether what I am writing fulfills the "requirements" of what I want to do. In fact, even outlining these requirements is pretty hard, but the fact that there is no way to check whether my writing "performs well" makes it extremely easy to give up.

* Problems with my normal writing process

** I am very bad at parsing written text quickly

Despite not being a big "visual thinker", I am very bad at parsing text quickly. That is not only a me problem, clearly text is much harder to parse than other visual information: it's much easier to look at a painting and recognize whether it depicts a face accurately (or at all) than to look at a piece of text and decide what it is describing.
Text is just a lot more information dense than visuals, which leads to you skimming over it. That's why graphs are much better than tables for quickly gaining an understanding of the data.
