#+title: The configuration space approach explains the possibility of anyons, not their occurence
#+roam_tags: anyons FQHE

* The configuration space approach to quantum statistics does not (aim) to explain /when/ anyons /will/ occur, just that they can/have to occur in two dimensions.

I was very confused about the role of the use of the [[file:20210218153716-configuration_space_framework_for_identical_particles.org][configuration space framework for identical particles]] for describing anyons/the quantum hall effect, as it felt superfluous when the /appearance/ of [[file:20210218152830-fractional_quantum_statistics.org][fractional quantum statistics]] in  [[file:20210219125155-the_fractional_quantum_hall_effect_fqhe.org][the Fractional quantum hall effect (FQHE)]] is justified/calculated using the [[file:20210312130104-berry_connection.org][Berry Connection]], which has no real clear tie to the configuration space framework.

I now realize that the configuration space "explanation" is not used to justify (or perhaps even explain) the appearance of fractional statistics in the FQHE, but to explain [[file:20210218152909-anyons.org][anyons]] wholesale!

The result of the explanation is that, in 2D, you /have/ fractional statistics. It also seems to imply that /only/ in 2D can you have fractional statistics, by showing how you cannot have fractional statistics in 3D. With this I disagree, but not with the claim that in 2D there will be  fractional statistics, and this is good to remember.
