:PROPERTIES:
:ID:       e94cf4f9-71a7-4717-a9b7-5881c3679461
:END:
#+title: The configuration space approach explains the possibility of anyons, not their occurence
#+filetags: anyons FQHE

* The configuration space approach to quantum statistics does not (aim) to explain /when/ anyons /will/ occur, just that they can/have to occur in two dimensions.

I was very confused about the role of the use of the [[id:c4cfc3fd-c497-44b6-80b3-a2ae6b35047b][configuration space framework for identical particles]] for describing anyons/the quantum hall effect, as it felt superfluous when the /appearance/ of [[id:479d3088-01ee-4224-86e8-e7ada158f9fe][fractional quantum statistics]] in  [[id:2fa90488-38aa-478f-bc3a-2290fb9def10][the Fractional quantum hall effect (FQHE)]] is justified/calculated using the [[id:3dad96b9-a6bf-449f-981e-4e141f865dd5][Berry Connection]], which has no real clear tie to the configuration space framework.

I now realize that the configuration space "explanation" is not used to justify (or perhaps even explain) the appearance of fractional statistics in the FQHE, but to explain [[id:31cd49eb-770f-4d11-98b2-ca666b534201][anyons]] wholesale!

The result of the explanation is that, in 2D, you /have/ fractional statistics. It also seems to imply that /only/ in 2D can you have fractional statistics, by showing how you cannot have fractional statistics in 3D. With this I disagree, but not with the claim that in 2D there will be  fractional statistics, and this is good to remember.
