:PROPERTIES:
:ID:       3dad96b9-a6bf-449f-981e-4e141f865dd5
:mtime:    20210701200816
:ctime:    20210312130104
:END:
#+title: Berry Connection
#+filetags: definition physics FQHE

* Berry Connection

\begin{align}
    \mathcal{A}_{\eta_i} =& -\frac{i}{2m}\sum_{j\neq i} \frac{1}{\eta_i-\eta_j}+\frac{i\bar{\eta}_i}{4ml_B^2}//
    \mathcal{A}_{\bar{\eta}_i} =& ++\frac{i}{2m}\sum_{j\neq i} \frac{1}{\bar{\eta}_i-\bar{\eta}_j}-+\frac{i\eta_i}{4ml_B^2}
    \label{eq:berryconnection}
\end{align}


* Backlinks :noexport:
** 3 linked references
*** [[id:e94cf4f9-71a7-4717-a9b7-5881c3679461][The configuration space approach explains the possibility of anyons, not their occurence]]
**** The configuration space approach to quantum statistics does not (aim) to explain /when/ anyons /will/ occur, just that they can/have to occur in two dimensions.
I was very confused about the role of the use of the [[id:c4cfc3fd-c497-44b6-80b3-a2ae6b35047b][configuration space framework for identical particles]] for describing anyons/the quantum hall effect, as it felt superfluous when the /appearance/ of [[id:479d3088-01ee-4224-86e8-e7ada158f9fe][fractional quantum statistics]] in  [[id:2fa90488-38aa-478f-bc3a-2290fb9def10][the Fractional quantum hall effect (FQHE)]] is justified/calculated using the [[id:3dad96b9-a6bf-449f-981e-4e141f865dd5][Berry Connection]], which has no real clear tie to the configuration space framework.

*** [[id:23e0cf04-bd7f-4c24-bdd0-7f65dea6df6b][Fractional statistics can only be calculated using adiabaticity]]
**** Fractional statistics can only be calculated using the assumption of adiabaticity
[[id:313f0a05-b6e3-43f8-8f2f-f004790dc798][Fractional Quantum Statistics]] that appear in the quantum hall effect are calculated with the [[id:3dad96b9-a6bf-449f-981e-4e141f865dd5][Berry Connection]]  using the assumption of [[id:75068634-a939-42ae-815f-8c31d02cf5f5][adiabatic theorem (quantum)]], which says that a things won't move out of the ground state if you move it very slowly.

*** [[id:41ef8c58-7d6d-413d-8f32-0e2b04c7949d][Quasi-things Have Charge e/m]]
**** Quasi-holes/particles carry charge e/m › Berry Connection
The above "proof" is rather shoddy. However, we can make a more educated guess by looking using the [[id:3dad96b9-a6bf-449f-981e-4e141f865dd5][Berry Connection]]

** Unlinked references
[Show unlinked references]
