:PROPERTIES:
:ID:       e6303312-f094-4dd9-9d74-568bd31a89ea
:mtime:    20210701200806
:ctime:    20210327154504
:END:
#+title: The configuration space explanation of anyons
#+filetags: anyons

* The Configuration Space Framework explanation of anyons

** Step 1: Construct the configuration space for the exchange of N identical particles in $d$ dimensions.

.
.
.

\[\tilde{Q} = \frac{\mathbb{R}^d-\Delta}{S_N} \]

With $\~Q$ said configuration space, $\Delta$ the "set of diagonal points in $\mathbb{R}^{Nd}$, which represent all points where the particles coincide", because fermions cannot be in the same place.
$S_N$ is the permutation group, which need to be divided out because the actual physical situation is the same for $(x_1, x_2)=(1,2)$ and vice versa. Exchanging them still changes things, but it does not matter which particle starts where.





** Step 2: Show that the space is not simply connected.

Because of the exclusion of the diagonal elements $\Delta$, space is no longer simply connected.

(I can see why this is the case in two dimensions, but this is not the case in 3 right?)



** Step 3: Prove that quantum mechanics can be done in this space



** Step 4: Show what the fundamental group is of $\tilde{Q}$ in 2D and 3D

The [[id:a07166f2-4a5c-40e6-a312-bc04b1b3d97e][fundamental group]] of a configuration space $Q$ is denoted by $\pi_1(Q)$

\begin{equation}
\pi_1(\tilde{Q}_{d=2})=\frac{\mathbb{R}^d-\Delta}{S_N}
    \label{eq:fundgroup2d}
\end{equation}
