#+title: EIA needs to be tackled on both premise 1 and 2
#+roam_tags: thesis idealizations EIA

* Context

My thesis for a large part consists of trying to undermine the [[file:20210204161810-enhanced_indispensability_argument_eia.org][enhanced indispensability argument (EIA)]]. However, I have been unsure about how to tackle this, because tackling the first premise of the argument can quickly lead to discussions of realism in general, but tackling the second premise is too limited in scope.

* Body

Solution: you can tackle the EIA in two ways, but they aren't coreferential with the premises.

** Indispensability

You can tackle the second premise by showing that the things in your explanation are not indispensable. Therefore, you counter any inference that these entities are real, such as mathematics or something. This is very strong, and works well. What you cannot do however, is show that the /explanation/ is not valid.

** Explanation

If you want to focus on explanatory power instead, you kind of tackle P1 and P2 separately.
P2 you tackle by showing that X is not indispensable to our best scientific explanations, as X does not factor in an explanation at all.
P1 you tackle by showing that the thing X helps explain, say, Y, does not constitute an explanation, OR it does not constitute an explanation strong enough to factor into p1, see [[file:20210204162417-pragmatic_explanations_cannot_lead_to_platonic_conclusions.org][pragmatic explanations cannot lead to platonic conclusions]]. By doing this, I still get to make my point about explanations without talking too much of indispensability, but I get to avoid the discussion of realism.[[file:20210204162914-talking_about_realism_directly_is_unproductive.org][talking about realism directly is unproductive]]
