:PROPERTIES:
:ID:       f5e4542f-0c24-4f50-bdfc-5e6d39ab8001
:mtime:    20210701200845
:ctime:    20210204155921
:END:
#+title: if you cant loop back to your introduction, make shit up in your conclusion
#+filetags: writing thesis

* Context

Had a chat with Guido and Ronnie about my thesis, where we discussed my introduction ([[id:fc0a61f3-2c05-4c30-ac48-08b84203010a][Proselike introduction v1]]). I worry too much about making true the things I put in my introduction.

* Body

It doesn't really matter if I make true the things I put in my introduction or not, and it is not wasted effort if I turn out not to be able to loop back around to the introduction.

I currently have this issue with my talk of boundaries: I worry whether I need to include it. However, it is not important at the moment whether I will be able to write something useful about it, I can still include it. If it does not end up making the introduction, I can still put it in the conclusion as "further research" or whatever.

So don't worry about whether or not you will be able to revolutionize philosophy of language: you can still talk about boundaries, it's okay.
