#+title: supervaluationism
#+roam_tags: vagueness


* Body

Supervaluationism is a way to deal with [[file:20210114163906-vagueness.org][vagueness]].

It is a [[file:20210114164133-de_dicto.org][de dicto]] account of vagueness, meaning that it ascribes a de dicto reading to vague statements such as

It is unclear whether someone that is 1.80m tall

The de dicto reading claims that it is indeterminate whether a person 1.80m in height falls within the set of bald people. However, the set of bald people is determinate.

The de re reading clamins instead that the set of all bald people has fuzzy boundaries, i.e. it just is the case that there is no fact of the matter where the edges of bald people are.

Supervaluationism is based on the idea that vagueness could be removed under some sort of precisification, e.g. baldness could be precisified as meaning "having less then 1000 hairs on ones head". The problem with this is of course: which precisification is right? This cannot easily be said, but thaat's okay: supervaluationism claims that there are clearish cases of good precifications (<1000 hairs) and clearish cases of bad ones (<100000000 hairs). Supervaluationism then introduces two new concepts: super-truth and super-falsity

** Supers

*** super truth

A statement containing a vague predicate is super true if(f?) the statement is true under all admissable precifications.

"A person with no hairs on their head is bald" is then super true, because every way of precisifying "is bald" would include the case of a person with literally no hair on their head.

*** Super falsity

Just the same but the other way around
"A person with 1 milliion hairs on their head is bald" is super false, because every way of precisifying "is bald" would rule out the caase of a person with 1 million hairs on their head.

*** borderliners

The only ill defined cases then are those which are not super true or super false i.e. those that are only true under some precisifications and false under others, such as having 10,000 hairs on ones head.

**   Logic
Supervalationism is compatible with classical logic, as we can just equate super truth to truth and super falsitity to falsity.

I don't know what we do with borderliners.
