#+title: Thesis sources
#+roam_tags: thesis reference

* Thesis sources



  Here I want to compile a relatively complete list of all my sources with some short descriptions of why they are useful. I have not found a better way to do this yet: Zotero is nice, but a bit opaque, and separate files are also nice but make me forget where I put them. This is something in between, which kind of sucks, because I have to do it manually, but that will also strenghten teh connections in mah brain, or something


  This also allows me to more easily assign them tags etc based on org-stuff
** Anyons

*** Katanaev 2011: Geometric interpretations of the AB phase

    Gives a freaking geometric interpretation of the AB phase!!!!!
  cite:Katanaev2011

Difficult to read though, and not very clear. Does not really seem to have caught on.

*** Shech 2015: Two Approaches to Fractional Statistics in the Quantum Hall Effect

    Shech aims to show that
    a) The topological approach to the quantum hall effect is problematic
    b) There is a better explanation, namely the geometric explanation
    c) We could still do topological explanations as useful explanations, don't need to discard them, they provide structural explanation while the geometric one only provides specific, agreeing sort of with cite:Batterman2001 here.

=THIS FUCKING SUCKS AS IT WAS EXACTLY WHAT I WAS PLANNING ON DOING AHHHH=
    cite:Shech2015b

*** Shech 2019: Fractional statistics etc etc

   cite:Shech2019
Here Shech goes in a very different direction than he did above, namely he argues

a) The FQHE only has one good explanation: the topological one
b) The topological explanation cannot be approximatley instantiated, unlike what cite:Leng2012 claims
c) By the [[file:20210204161810-enhanced_indispensability_argument_eia.org][enhanced indispensability argument (EIA)]], we have to believe that the topological idealization is in some way real.

   Then he claim some additional annoying things regarding that this is not possible.

   Also has useful discussion of how  [[file:20210327154504-the_configuration_space_explanation_of_anyons.org][The configuration space explanation of anyons]] works.

*** Roa 2001: An Anyon Primer

    Very useful explanation of the configuration space explanation of anyons, and some other useful discussion surrounding it.
cite:Rao2001

*** Brown 1999: Remarks on Identical Particles in de Broglie-Bohm theory
   cite:Brown1999

   Article by Guido and some other people about how to derive the topological explanation of anyons. Pretty interesting but ultimately not very useful.
** Geometric Phase

*** Cohen et al. 2019: Geometric Phases From Aharonov-Bohm to... :review:
cite:Cohen2019

Pretty good review of what a geometric phase is and where it has been fruitfully applied.

*** Ong 2006: Geometry and the Anomolous Quantum Hall Effect in Ferromagnets

I think it will give a good explanation of how things work with geometric phase etc, it even gives explicit analogies with the cone!

Important: this looks at the /anomolous/ hall effect, which is the Hall Effect applied to a ferromagnet. What happens here is not per se that you get anyons, but you get electrons which pick up a different phase because of the magnetic field, similar to the AB Effect.

   cite:Ong2006

* Backlinks :noexport:
** No linked reference

** Unlinked references
[Show unlinked references]

* Backlinks :noexport:
** No linked reference

** Unlinked references
[Show unlinked references]

