:PROPERTIES:
:ID:       2380111f-1558-4b59-aeaf-ffec7c7f70d9
:mtime:    20210701182509
:ctime:    20210518164940
:END:
#+title: email to guido and ronnie about geometrical phase
#+filetags: geometric_phase email

* email to guido and ronnie about geometrical phase

Dear Guido and Ronnie,

As promised, and characteristically a little later than usual, a little update about my ongoing battle with the quantum hall effect.

I was going to update you around a week ago with (if I remember correctly) whether I would be able to calculate the phase of the quasiparticles geometrically, rather than describe them topologically as is the case with the usual configuration space explanation. I can say that I am/would be able to, but that I am once again a bit lost on both the mathematical and conceptual front. First, the calculation.

*The calculation*

The calculation of the Berry phase is in general not very complicated. In short, it is
\[e^{i\gamma}=\exp\Big(-i\oint_C \mathcal{A}_i(\lambda)d\lambda^i\Big)\]
where $\mathcal{A}_i$ is the so-called 'Berry-connection', defined as
\[A_i(\lambda)=-i<\psi|\frac{\partial}{\partial\lambda^i}|\psi> \]
