:PROPERTIES:
:ID:       a3694051-3129-4f3b-873d-3fdb385bcdab
:ROAM_REFS: cite:Dougherty2020b
:END:
#+TITLE: Dougherty2020b: The non-ideal theory of the AharonovBohm effect
#+ROAM_KEY:
#+FILETAGS: reference explanation anyons idealization


* The non-ideal theory of the AharonovBohm effect
  :PROPERTIES:
  :Custom_ID: Dougherty2020b
  :DOI:
  :AUTHOR: Dougherty, J.
  :NOTER_DOCUMENT:
  :NOTER_PAGE:
  :END:



* Summary

Responds to cite:Earman2019 and cite:Shech2015b,Shech2018   Says that they claim that the /topological/ interpretation of the AB effect is unsatisfactory, and defends it, based on three main points:

- The AB effect does not use a singular limit, unlike what is claimed
- We don't need to focus on bounrady condiitions that much
- It's okay that we use non-relativistic qm for the description of the ab effect, but only because it places constraints on the RQM, we don't take it as the final description.


* Rough note space

" The perfect shield is used mostly for draa, much like the moon's negligible atmosphere can be used for a striking demonstration of Galileo's law of free fall." ->He thinks that AB effect is non-problematic idealization, as in [[file:infinite_idealizations_chapter.org][What is an infinite idealization (Chapter)]]


** Useful summation of other lit

cite:Butterfield2011,Callender2001,Menon2011  and  Palacios 2018 argue that the thermodynamic limit is fake, while Bangu 2009, cite:Batterman2005 Batterman2011 and Morrisson 2012 say that it is essential.

** angery
Shech claims that the "topological" view of the AB effect is in contradiction, on grounds of the following four claims

1. Real systems consist of a simply connected electron configuratoin space.
2. Real systems display the AB effect.
3. the AB effect occurs if and only if there is a non-trivial relatiev phase factor.
4. A non-trivial relative phase factor arisis if and inly if the electron configuration space in non-simply connected. 4847


The first two say that space is simply connected, while the last three say that real systems are non-simply connected in virtue of displaying the ab effects.

He thinks that "implementation details are besides the point" 10

After some faffing about, he replaces the set of 4 propositions by

1. There is a contractible spacetime region containing the AB apparates.
2. The AB apparatus displays the AB effect
3. The AB effect occurs if and only if there is a nontrivial phase factor.
4. A nontrivial phase factor arises only over a noncontractible region. <- Topological view (according to dougherty )

   So, /crucially/: Dougherty claims that we shouldn't think about configuration spaces, but about /regions/. Regions can very well differ in their connectedness/contractability, whereas configuration spaces, given that they are global things, are not.
Furthermore, apparently we can "/neglect the contributions from paths which intersect the shield/", which sounds wild. FURTHERMORE, he claims that this /isn't/ an infinite idealization. Let's see what he comes up with.
[[file:20210503131837-topological_explanation_merely_requires_multiply_connected_regions_not_configurations_spaces.org][Topological explanation merely requires multiply-connected regions, not configurations spaces]]

He does allude to the topological interpretation being useful because it makes a universal claim rather than the specific claim if we don't, similar to what cite:Batterman2001 and  cite:Strevens2019a think.

Topological view = qualitative view

** Idealizations

It seems like Dougherty is arguing in favor of seeing things as /effectively/ topological, which I think is a very strange positon: i'd think that you would /either/ that the effect is effectively observed (some idealization is effectively true) /or/ that it is topological: is this a mismatch of terms?
Specifically, he says: "If the shield is imperfect then the interference observed in the lab will also have contributions from paths that penetrate the shield" page 15. this is strongly informed by him seeing the effect as being due to "non-contractible regions" rather than non-simply conneted configuration spaces.

Which is all very strange: he furtermore says: "the topological view only suossed that the contributions from paths that iniresect the shielding can be effectively distinyguished from the contribuitons from the paths of interest." But I thought it didn't? Doesn't the topological view need, at least, non-contractibility, which you cannot have it paths intersect the solenoid?

Interesting claim: "on the topological view, the AB effect requires only theat

\begin{equation}
\int Dxe^{\frac{i}{\hbar}S_{A')(x)}} -  \int Dxe^{\frac{i}{\hbar}S_{A)(x)}} \neq  \int_{shield} Dxe^{\frac{i}{\hbar}S_{A')(x)}} - \int_{shield}     Dxe^{\frac{i}{\hbar}S_{A)(x)}}
    \label{eq:abeffectreqs}
\end{equation}

Where A' and A are equipotent potentials with different pointyboys (gauge potentials?)

I don't fully understand the above, but I do realize it's a signifactly different picture from what is normally seen as the "topological AB effect"

Even more strongly, Dougherty claims that modelling "the shielding of the electromagnetic source as an infinite barrier [...] isn't part of the AB effect."26
