:PROPERTIES:
:ID:       fc0a61f3-2c05-4c30-ac48-08b84203010a
:mtime:    20210701200531
:ctime:    20210701200531
:END:
#+title: Introduction Chapter
#+FILETAGS: chapter structure introduction thesis

* Introducion/Discretization

As I see it, the chief problem of philosophy is to explicate how, if at all, our language relates to the world. This is not a new thought, but one I wish to explore in this thesis.

** Specifically: words seem to denote a very precise ontological thing, but our epistemological capacities arent that precise

I believe there exists a massive mismatch between the way we use language (names and/or concepts in particular) and how we conceptualize the ontology of the world. In short it is this: the _names_ we use for objects and _concepts_ in our language are discrete, while the space underlying them is continuous. That is, while we use names and concepts as if they have a definite _boundary_, there does not seem to be a clear line we can draw between the object and not-object, the concept and not-concept. Their boundary seems to be _vague_, indeterminate, fuzzy, etc.

(this is not really a good example, I could start with "human" or "the human that X" or something. It's a much more familiar and vivid example, but it does veer into philosophy of biology more easily, so I'm weary to use it as a starting off point. Ideally I'd use a physics example but I don't have one that's quite so vidid as "human")
Names and the objects they refer to are discrete in the way that one definite signifier is intented to represent one definite object or kind of object (natural kinds, I think): it is implied that the name refers to something with a definite spatio-temporal boundary. The problem of vagueness arises from the contrast between this proposed definiteness of boundary with the actual continuity of space, which does not lend itself to having distinct, point-like boundaries. In some cases this is more apparent than others. Take the name "the football used in the 2016 world cup finals" and the object it refers to, the actual football. The name implies, by use of "the", that there is one unique object, the actual football, it describes.

At first glance this appears uncontroversial: there is only one football which was used during the final, no exchanges were made and no "multi-ball" rule was suddenly introduced. The issue however is that we do not believe that footballs are fundamental constituents of reality, were there to be such things as fundamental consituents of reality. Instead we think that footballs are composed of smaller objects which may be fundamental consituents of reality, such as molecules, atoms, protons, quarks, and so forth. This fact leads to there not being a one to one mapping between the name "the football used in the 2016 World Cup finals" and a definite set of fundamental consituents of reality in a number of ways.

The first is a basic line drawing problem. This problem in fact already presents itself without thinking of the football as being composed of smaller consituents, as it is a consequence of the presumed continuity of space. It is not possible to pinpoint the exact location where the ball begins and ends, simply because it is not possible to measure a real number.

The second is due to specific physical theories: because of the uncertainty principle, there simply is no fact of the matter where the final electron belonging to the football and not to not-the-football is located in space, except of the De Broglie-Bohm interpretation, which is not per se popular.

The third and final issue with delineating the football is a more familiar matter: our idea of "the football" is not so fine-grained as to allow for the minute differences that happen to the football over the course of even a second. Kicking the football will result in some molecules separating from the main clump, perhaps adding some from the dirt, some of its atoms will decay, it will radiate away some heat and absorb some more: the exact state of the football changes across its life, second to second, moment to moment.

This third problem is best conceptualized using the Sorites paradox, which is not specific to names but to properties and concepts more generally as well. The basic idea can be summarized as follows: ten thousand grains of rice makes a heap of rice (or X collection of atoms make up "the football"). 9.999 grains of rice still make up a heap, as does 9,998. It appears that if N grains of rice make up a heap, then N-1 grains of rice also make up a heap. However, by mathematical induction, this would force us to conclude that any x grains of rice makes up a heap, including 1 grain of rice, which is patently false. To combat this, we can postulate that there exists a definite boundary between "being a heap" and "not being a heap". However, since the only way in which we can affect the heap is by adding or subtracting a grain of rice, this would lead to the other false conclusion that there exists an x such that X grains of rice do not make a heap while X+1 grains of rice do make a heap, which goes against the premises of the first argument: a true paradox.

** I don't want to directly tackly meaning/vagueness/boundaries because it's hard. Instead I will look at physics because I know physics, and they sort of do this

These problems are deep and substantial, and while tackling them head on might be an option, I instead wish take a more roundabout route for exploring them by relating them to an area that explicitly deals with making precise denotations of an continuous mess: physics.

** Physical Models/Idealization

I take it as uncontroversial that physicists construct models, such as the Standard Model of Particle Physics, with a goal being to, at the very least, at some point make predictions about the outcomes of experiments. I furthermore take physics to be that what physicists do. Therefore one of the goals of physics is to construct models which make accurate predictions about the outcomes of experiments. This is a very conservative picture of physics.

** Physics is a good case study as they use models which are analogous to the thing im interested in

The link between physics and the way words represent concepts becomes more clear when taking a slightly more ambitious stance towards the enterprise of physics, namely as constructing models which, in one or more aspects, _represent the world_. Representing an aspect of the world through a model is analogous to representing an object by a name, or more generally a concept by a word: continuous nature is fit into rigid molds. Investigating this link, therefore, might show us something about language more generally.

** Too difficult on its own, let's just look at idealizations or abstractions

However, attempting to evaluate how, if at all, physics represents "reality" directly proves no less difficult than attempting to determine that for words, concepts, objects, natural kinds etc. in general. Here, too, we need to narrow our scope to attack this question in any sensible way. I propose that the relevant aspect of physical modelling lies in its employment of idealizations and abstractions in order to simplify the mess that is continuous reality.

Although the nature of idealizations and abstractions (henceforth I will just write idealization) will be spelled out in more detail later, it is worth noting some of its basic features and some similarities with the larger issue of denotation.


(For the moment I will treat idealizations and abstractions as basically being the same thing, idealizations probably being more specific than abstractions. It is important and necessary to determine whether these do amount to the same thing however, see for instance cite:Shapiro2004, cite:mancosuAbstractionInfinity2016, cite:Lutz or cite:Knox2016 or cite:2016
Although one clear difference does already spring to mind: idealizations are usually strictly false, while abstractions are more akin to generalizations, in that they are not false but simply cover more phenomena. Idealizations might not be a subtype of abstraction, but maybe a feature of it. I might start by introducing abstractions first, then focusing on idealizations later as a way to tackle that, but I am not sure of that step yet.)

** Why should we pick idealizations

   The solution is to pick specific aspects of a model that get close to the problem at hand. To this end I suggest using the idea of an "idealization", as idealizations are somewhat analogous to what I see as discreitziation, and are an import component of models. One of the key tasks will be to first flesh out the concept of an idealization, how necessary they are to models and how the relate to discretization. This will be done in chapter [[file:../../.local/share/Trash/files/20210106131334-chapter_idealizations_meta.org][Chapter Idealizations (meta)]]. I will specifically have a look at a subclass of idealizations: infinite or infinitesimal idealizations. This is because I believe they highlight what goes wrong with idealizations more clearly in a way that mirrors the general problem of discretization.

** TODO Why Infinite idealizations
*** Actual reason: (Shech makes this literal argument)
*** What is an infinite idealization

An infinite idealization is an idealization in which some relevant property is set to 0 or infinity, rather than approximating it as being arbitrarily small or large.

*** How does it differ from a normal idealization

Infinite idealizations differ from "normal" or simple idealizations, to borrow cite:Strevens2019a 's terminology, in which a value is simply set to some other value.

*** What's the goal of an infinite idealization

First we must separate what an infinite idealization does from what it is meant to do.

*** Infinite idealizations lead to problems
**** Limit system does not exist
**** Limit system disagrees with actual system
** EIA
*** Physical models and their idealizations are only a good case study if they are claimed to represent trutfully/literally

The relation between idealizations/abstractions and aspects of the world does not prove to be such a direct candidate for comparison between names and objects so easily, as there exists an important difference between the rough picture of physics sketched above and the question of how to match the discrete objects to continuous "name space": the models of physics do not per se truthfully represent the world, at least not until we stipulate such a thing. In contrast, when talking about the problem of discrete names not matching their continuous objects, the problem only arises when we imagine the word to truthfully represent the object, or, less strongly, to factor into true propositions about that object e.g. "the football is round". Similarly, models can only be used to study the boundary problem if we stipulate that the truthfully represent the world in some relevant aspect. (the relevant aspect quantifier is there because we do not expect our current models to grasp every relevant structure of the world, e.g. no emperically backed theory of quantum gravity exists as of yet.)

*** Scientific realism claims that the idealizations truthfully represent

Fortunately, a rich philosophical tradition exists which espouses just the view that physical models truthfully represent, at least in some respect, the world: scientific realism. This tradition is no monolith however, and many competing and often incompatible interpretations exist, some more modest than others. More conservative, modern takes on the subject such as the structuralist realism espoused by James Ladyman and John Ross, are not easily said to believe that physical theories "represent" some relevant aspect of the world, rather they claim that such models "latch on" to relevant structures of the world, whatever they may be.

*** The EIA as a case study/representative of scientific realism

For the purposes at hand, namely to elucidate how, if at all, the continuum can be discretized, it is more instructive to at least initially turn our gaze to stronger, more bold variations on scientific realism. The strongest seriously discussed version of scientific realism are based on Putnam-Quine style indispensability arguments, the "naive" version of which goes as follows:

**** "Naive" Indispensability Argument

    1. We ought to believe in the existence of those entities which are indispensable to our best scientific theories.
    2. X is indispensable to our best scientific theories
    C. We ought to believe in the existence of X

   The "naive" is put in scare quotes here because this version of the indispensability argument has (more than) one shortcoming, in it leaving unclear what being indispensable to a scientific theory entails. What is it to be dispensable to a theory? To solve this, the modern form of the argument, the "Enhanced Indispensability Argument" (EIA), is used instead, which goes as follows:

**** Enhanced Indispensability Argument (EIA)

   P1. We ought to believe in the existence of those entities which are indispensable to our best scientific explanations
   P2. X is indispensable to our best scientific explanations
   C. We ought to believe in the existence of X

The focus has now shifted from indispensability for our best scientific theories to explanations in stead. This move is motivated by two thoughts. For one, it assumes that to succeed as a scientific theory is to offer a good explanation, or at the very least that providing a good explanation is good enough grounds to believe in its existence, provided that being indispensable to our best scientific theories is more than sufficient already. That is, offering good explanations is a necessary condition for being a good theory, as we do not think a theory succeeds without it. It is close to being a sufficient condition for constituting a good scientific theory as well, but I am hesitant to claim so on the grounds that what consitutes a "good" explanation is rather contentiuous, as we shall see, and that the number of phenomena a theory can explain does seem to matter as well. I do not believe that an extremely specific theory which somehow makes little to no reference to existing theories and is able to explain a single phenomenon well would count as a succesful one (although it might be argued that calling this an explanation would be questionable, but I digress).

Second, it carries with it the hope that "being indispensable to explanation" is easier to clarify than "indispensability to a theory." This second thought requires one to buy that a) scientific explanation can be satisfactorily defined and delineated from not-"scientific explanations", which includes both non-explanations and non-scientific explanations (henceforth with "explanation" I will mean "scientific explanation" unless otherwise specified). Furthemore, it requires us to find plausible that b) finding that which is indispensable for those explanations is more straightforward than for theories as a whole. I will not grant these moves immediately and will scrutinize them in what's to come.

*** What can the truth or falsity of the EIA possibly lead to

Before saying why looking at the Putnam-Quine argument could provide us insight on the much more general problem of discretization, let us first evaluate what sort of conclusions we could draw from our investigation. To start, let us say that thoroughly examining the Putnam-Quine argument leads us to consider it a valid form of inference to the actual consituents of the world, and furthermore we find entities or other things for which the argument holds. Our quest would then be complete, as we have found a way to justify dividing up the continuum of space and time (or "thought space" in the case of mathematical objects) into discrete, consituent parts (given that the entities which enter in the argument are discrete, which I will argue later they are). This provides a sufficient answer to the "if at all" part, and sheds some light on the "how" part, though does not exhaust the possibilities. For instance, it would provide little clarity on how, if at all, we do so in ordinary language when talking about footballs and tables, except if we take the EIA to be an exhaustive guide to all actual entities, something which the argument cannot entail in its form stated above.

*** If we were to find that (infinite) idealizations do not factor into the EIA, why is it useful for the main problem of "discretization"

As the reader might have expected, I am not so optimistic about the EIA's chances of meeting the demands to be spelled out. How, then, would investigating it yield us any fruitful information about discretization? For if the EIA does not turn out to be a valid form of inference for determining the discrete parts of reality, it would not rule out the possibility of doing so, much less show us why it is impossible in the first place. In particular, the EIA provides a sufficient condition for something to have ontological status, not a necessary one. Therefore failing to be indispensable to explanation does preclude any entity/structure from having ontological status. (Is this true? Is the EIA not "those and only those"?)
This concern is real and valid. In fact, finding that the EIA is not valid would not rule out anything about the discretization on its own. Instead, the EIA provides a case study in which to more concretely tackle an instance of this problem, and my hope is that by examing its workings applied to specific examples to be expounded upon below, we might learn something valuable about the more general problem in the process. Given the scope and generality of the issue, it would be extremely optimistic to hope to solve it in a lifetime, much less one thesis, so my aims are more humble: to extract from the EIA some valuable lessons for tackling the discretization problem (or whatever you want to call it.)

*** Why it's worth looking at idealization at the EIA (again)

As mentioned previously, we seem to have lost the "how" in the "how, if at all" formulation of the main question in the step of attempting to apply the EIA to idealizations. One argument in favor of this step is that it is a necessary condition for explaining "how" something works, /that/ it works at all first. Additionally, the hope is that by showing "how not" the EIA, we learn something about "how not" to answer the question of discreteness. While the possibilities for discretization are technically endless, humans only need a finite number of counterexamples in order to be dissuaded of the usefulness of something. This rather severe limitation might then be a better starting point: to provide reason for distrusting discretization of continua, rather than providing a direct counterargument. If a direct counterargument comes up, so much the better. If we end up concluding that (infinite) idealizations cannot factor into the EIA, at least we have something.

*** Two ways of evaluating the EIA: P1 and P2

In order for the EIA to be a sound argument, its premises must entail its conclusion and its premises need to be true. The argumentative structure of the EIA is as straightforward as it gets, so it is valid. The premises, however, are controversial to say the least. Therefore the soundness of the EIA hinges on the acceptance of its premises, meaning that there are two ways the EIA could fail: either it is not true that we ought to believe in those entities that are indispensable to our best scientific explanations, or the relevant entity X is not indispensable for our best scientific theories. Let us say something about each of these in turn.

**** What does arguing against premise 1 give us

Regarding permise 1, arguing against the premise that we ought to believe in those entities that are indispensable for our best scientific theories is arguably the strongest move one could make, as it prevents the argument from taking off at all. Such a line of argument is common among anti-realists.

**** Why not to tackle premise 1

However, I would prefer not to take this line of argument for two reasons. For one, I feel it is not so convincing to the putative realist. Many convincing anti-realist arguments have already been made by van Fraassen etc, so I find it unlikely I would be able to sway a realist by making such an argument. Secondly, a succesful argument against premise 1. would take the form of one of the following:
a) argue against explanations, either playing a (crucial) role in forming our explanations or the possibility of explanations in general
b) argue against indispensability as a criterion for belief in entities
c) argue against believing in entities, whether some specific entities or entities in general.

a) and b) would not entail much at all about the discretization question, while an argument for c) could instead directly be used as an argument for the main problem or again not entail much, as "we ought not to believe in the existence of entity X" would simply remove X from the list of things to consider demarcatably, while "we ought not to beleve in any entity X (which has certain general properties)" could be reformed as "we are not able to demarcate discrete objects with property X", which defeats the point of using the EIA at all.

**** We should look into premise 2 instead

   Therefore, I wish to focus on premise 2: X is indispensable to our best scientific theories. One might immediately object that this is subject to the same charges as before, namely that looking at some class of objects X, say electrons, will likely not entail much about the conclusion in general. The way around this is to pick our X carefully. A candidate could be models in general, as finding out that models are not indispensable would make us not have to believe in them, and if models are analogous to concepts in the sense that they discretize a messy continuum, this might show us something about how this is done in general. However, this is too broad a task, as (almost) all physical explanation concerns models and what consitutes a model is (ironically) difficult to define. This is then subject to the same charge as that for denying explanation outright, or just impossible.

*** Why not use this for premise 1 tho

But why can we not pick infinite idealizations for conclusion 1 instead, i.e. argue whether or not we ought to believe in the "existence" of infinite idealizations if they are necessary for our best scientific explanations, rather than evaluating whether they are in fact dispensable or not? Good question. I believe that arguing against the conditional, be that by denying the consequent or the antecedent, is getting ahead of ourselves. It makes the thing not so useful.

*** TODO MORE TEXT JUSTIFYING WHY IM TACKLING THE EIA ON ITS SECOND PREMISE GOES HERE
* On explanation

Before evaluating the indispensablity of certain entities/whatever to the purported explanation of physical phenomena, we need to come to an agreement how, if at all, these explanations explain.

The stance Shech takes to explanation is a sociological (?) one: explanations are what scientists call explanations. According to Shech, it is not the role of the philosopher to dictate what are good or bad explanations, to say what is good or bad science. "If one's favorite account of explanation does not account for the standard story [of explaining the FQHE], so much the worse for one's favorite account of explanation", he says determinately.

I am have two conflicting thoughts on the subject.

On the one hand, I agree that judging a purported explanation only by reference to "the" correct account of explanation is unwise. The decades long debate on explanation has yielded little in the way of consensus about the correct account of explanation, even by the low bar of what is considered consesus in philosophy. Even the deductive nomological account, while seen by many as fatally flawed by not being able to account for the assymetric nature of explanation or being able to distinguish explanatory relevant factors from explanatorily irrelevant ones, is still the most commonl way of explicating explanation, usually prefaced with a half-hearted acknowledgment that is indeed flawed and that these half-hearted apologetics for using it anyway are a cliche in themselves. Other accounts, such as the unificationist account by Kitcher and that other guy, the plethora of causal mechanical models, the interventionist account, mechanistic ones etc, while not enjoying the widespread adoption of the DN model, are still being argued over, with nothing close to a definitive distancing from any of them being the case.

Therefore, arguing the wrongness of an explanation based on it not fitting a certain model of explanation is not particularly convincing for two reasons. One, it requires one to first convince the reader that this account of explanation is the correct one (just trust me), which as seen above, does not seem particularly likely. Secondly, ??

On the other hand, however, I do not wish to simply do away with any sort of measure of explanatoriness (definitely a word) and to uncritically accept the explanations offered by scientists.

Could lead us to accept bad explanations. Supersymmetry?

How do we know when the scientific community has accepted something?

Treating the word of scientists as gospel like this does a disservice to them, as it sort of presumes scientists don't and moreover cant set critiria for what is a good explanation.

This division between philosophy and science seems kind of weird.

We might be able to identify some common criteria of those things we consider good explanations. For instance, we do not have strongly believe that super symmetry is a good exlpanation for (INSERT WHAT SUPER SYMMETRY EXPLAINS) anymore. Do we believe this simply because physicists have moved on or because there are good reasons for not believing its explanatory capabilities? The latter of course, empirical adequacy is a very important one, which is also a reason we don't consider most of the claims of string theory as explanatory correct.


However, we must be weary of not simpy defining another concept of explanation. Instead, there are two ways of evaluating the question "how, if at all, does theory/argument/... X explain phenomenon Y"?

1. Evaluate whether for every theory of explanation the theory explains. This is the most comprehensive way of tackling the question, and can lead to two answers, only the latter of which is really satisfying
   a) theory X explains phenomenon Y on accounts of theory of explanation A, B, and C, but not on account of D, E, etc. Therefore, if one believes theories A, B, or C to be the correct theory of explanation, the X explains Y.
      The problem with this is that either one ends up arguing for the validity of A B or C, which as discussed is dubious or simply leaves it up for the reader to decide for themselves if they believe A B or C, which lacks quite some argumentative force.
   b) according to all common theories of explanation A, B, ... X does/does not explain Y. Therefore it is plausible to assume X does/does not explain Y, as every theory agrees on the subject.
   Not only is this quite the amount of work, it is unlikely that we would reach such unanymous agreement, as some theories have widely varying criteria for explanation. Consider for isntance the differnce between causal mechanical and unifying explanations for instance: the former requires an account of how the phenomenon comes to be from the fundamental constituents of the thing and can decide per explanation whether it explains or not, while the latter only requires an explanation to group some set of phenomenon and is not able to say of an individual explanation whether it is "good" or not (as most explanations will probably unifity ~some~ phenomena), only whether one explanation is better than another. Comparing the question "account X constitutes as a good explanation for Y" (as we are interested in our "best" scientific explanations, whatever that may mean) for both the unficationist and the causal mechanical model will therefore prove quite challenging, as a good causal mechanical explanation is just a causal mechanical explanation, while the "goodness" of a unificationist explanation is much more graded.

   These are just some of the challenges that come to mind, but again I deem it unlikely unanymous agreement unlikely in the first place, let alone satisfactorily determining whether every explanation is adequate. Does the thermodynamic limit prove a good explanation under all these accounts? Causal mechanical it is certainly doubtful, although some have argued otherwise, see Strevens.

2. Determine some shared criteria all accounts of explanation (should) obey, and evaluate whether these explanations match these criteria.

   This method has two pitfalls

   a) If they obey all of the criteria, this does not mean that it is a successful explanation per se. The criteria only serve a negative purpose, barring would be explanations from attaining such status, as it provides only necessary conditions, no sufficient ones, by design.

   b) Being arbitrarily normative, or rather begging the question
      If one were to define exclusion criteria for what ought to count as explanation, we need to watch out that we do not beg the question. We must take great care to justify these exclusion criteria, otherwise it can come across as us simply taking elements from these explanations and labeling them as bad. Furthermore the risk exists of excluding an entire category of explanatory theories, which defeats the point.

      (This might happen for instance when one assumes that a good explanation ought to determine which objects in said explanation "make a difference", see e.g. cite:DeBianchi2016 )

**** TODO Figure out whether the difference maker discussion excludes the DN model or unificationist model
*** Goal of the explanation strategy

In short, the goal in this section is to identify exclusion criteria for explanations that do not
  a) have arbitrary justification
  b) exclude an entire theory of explanation
  c) postulate a new theory of explanation, i.e. be a sufficient condition for explaining.
     I am not exactly sure what this would look like, but I have one criterion that looks like this

*** Another objection

How /can/ you identify such criteria? What source of "explanation" are you drawing from? The platonic ideal of explanation?

This is a valid point, but one I can't really answer right now, maybe I'll have a smart reply later.

*** The criteria
**** TODO A lot. This will form the very foundation of my thesis, while being the most specific part. In order to give a better account here I need to look into the specific phenomena more deeply. What would I gain from that? I feel like I can formulate that to make sense somehow. Self-consistency? Is that different than non-contradiction? It's more of a given,
**** 1. To warm up, let us begin by defining the most basic criteria any explanation ought to satisfy: it needs to account for the actual empirical thing, save the phenomena as we are fond of saying.

   - Is this part of explanation or of a theory?

**** 2. It needs to follow some sort of "because" clause.

   - Very general

**** 3. ...
**** 4. ...
**** 5. It needs to create /understanding/ in some agent.

   This might the most crucial one and the most difficult to define. It does hinge on the question: do explanations exist independently of agents to understand them?
   While this is a difficult question to answer, we need not do so here, provided that it satisfies our earlier defined points, namely is it arbitrary, does it exclude an entire theory of explanation or does it postulate a new one. Let's treat them in turn

***** Arbitrariness

        I'd say no. While not unobjectionable, it certainly does not seem arbitrary or begging the question, as for instance a criterion such as "no infinities allowed" would be. Discussion s about udnerstanding and its importance for explanation have been held for a long time in otrher gidelds and have more recently come up in philsophy of science.
        Moreover it is at least pragmatically true that we would not be aware of any explanations that did not probive any

***** Exclude an entire theory of explanation

        While few of the majors actively include understanding, I argue that none would be significantly changed by including the requirement that they provide understanding.

***** Too sufficient

        This is arguably the biggest charge one could levy against this criterion, since "providing understanding" in the sense that someone understands a phenomena after hearing something which does that, sounds like it is explained to them. In order for it not to be sufficient, there need to be things missing from any (set of) proposition(s) which provide understanding, which need to be fulfilled in order to be considered an explanation.

        One thing that comes to mind is that the agent /thinks/ it gained understanding, but in actuality the "explantion" which did so is false. Conspiracy theories would constitute such a case: our agent might believe that they gained understanding of the increasing number of autism diagnoses by being "explained" that if you get vaccinated then you get autism (or become more likely to get autism) and that the number of vaccinations given has increased. However, the first premise here is false. Has the agent then gained understanding of the increased rate of autism diagnoses? Or more importantly, does the "explanation" count as an explanation?

        This would not count as an explanation on all counts of explanation.
        1. DN: requires all premises to be true. Premise 1 is not true. Therefore not an explanation.
        2. Causal mechanical: there does not appear that a true causal story of vaccines to autism can be told, therefore not true.
        3. Interventionist: difficult to tell. While for a single individual it might be possible to intervene here, take an individual without autism and give them a vaccine, see if they develop autism. However few would claim that every single vaccine would cause autism, as most of the world would then be on the spectrum. It seems a lot more difficult to intervene in the course of history and not vaccinate everyone and to then compare whether the autism diagnosis rate remains the same. Counterfactual speculation seems difficult here, therefore it does not appear to be a good explanation.
        4. Unificationist: as mentioned before, for unificationist accounts, "good" is relative. However, since we are interested in what our best scientific explanations are, we can compare this explanation of the increasing vaccine rate with a different one and evaluate which one has the greater unifying power. there's probably one right

    So it might not count as an explanation, mostly on the fact that it is not true or better explanations exist. However, does it count as creating understanding?

****** TODO Evaluate whether this counts as understanding

            - Find definition/theories of understanding
            - Apply them

**** 6. "It must match reality in some way"

This is definitely begging the question man, we are trying to find this very thing remember? The hell does matching reality mean.

**** 7. The explanation must not create a contradiction

Duh. This seems like to banal to even mention, not sure if I can draw some interesting conclusions out of this.

What I'm thinking about is the thermodynamic limit implying the existence of infinity particles, or FQHE implying 2D particles. However, I cannot take this as refuting the fact that they are explanations, as this is exactly the point of contention. Furthermore it's not a flat out paradox, as it is at least logically possible that some particles could be 2D, it is just very plausible /prima facie/.

(Ideally after this section I'd have some kind of idea/criteria for what to look for in a good explanation. My worry is that doing this /before/ looking at the actual examples I either miss things or end up defining criteria based on my discussion of the examples later, which messes up the structure. Therefore I am uncertain of the place of a chapter on explanations in the structure)

* Part II: The phenomena
** Limit explanation of phase transitions

In thermodynamics, phase transitions (such as water boiling, a magnet losing its magnetization) are represented by a non-analyticity in the relevant thermodynamic function (such as pressure or magnetization).  The issue is that we do not consider thermodynamics to be the final theory of the world, and in particular do not find it sufficiently explanatory. Moreover, we have a theory we consider to be more "fundamental" than thermodynamics, statistical mechanics, and would like to account for the phenomenon of phase transitions in said theory.

However, the issue arises that the only way in which to directly recapture the thermodynamic phase transitions using statistical mechanical tools is by taking the so called "thermodynamic limit", in which the number of particles is taken to infinity while the volume of said particles goes to zero, keeping the density constant. This is because the thermodynaic variables needed for describing the phase transition in statistical mechanics are derived from the partition function, which is a sum of analytic functions. In order for the thermodynamic variables to exhibit a phase transition i.e. a non-analyticity, the partition must contain a singularity. The partition function can only do so if either the energy of the particles is 0, which is impossible, or if the sum is infinite. This latter result is not trivial, nor is it straightforwardly a theorem, but it is commonly accepted as such, see Kadanov.

Therefore, in order to account for (to explain?) the phenomenon of phase transitions, it is claimed, the thermodynamic limit must be taken i.e. we need to make an infinite idealization. Moreover, it cannot easily be explained away by interpreting this "limiting operation" as an approximation, i.e. as one of simply seeing the the collection of atoms to be arbitrarily large. One cannot approximate a singularity: it is either there or not there. Therefore, only at N=infinity does the singularity present itself, not at any point beforehand.

However, some, like Norton, argue that the singularity is approximated in some sense that is useful, as the curve of the graph gets closer and closer to the one at N=infinity as N->infinity. The important point then is which property we consider.

** Aharanov Bohm effect

Something about a solenoid in a magnetic field, which needs to be infinite in order for the calculation to make sense. Something something Berry shift.

** FQHE

The classical hall effect is the phenomenon of measuring a transversal voltage when running a current through the long side of a metal plate, because of Lorentz afguiging. More electrons on the right then on the left, thus potential difference thus voltage.

The Quantum Hall Effect has two sub parts: the integer and fractional quantum hall effect. Let us start with the former. The integer quantum hall effect is observed when running a similar experimental setup to the classical hall effect, but with a much thinner and purer sheet. This gives weird plateaus at integer multiples of the quantum of resitance?. The explanation for these plateaus is some weird stuff about Landau levels, but is ultimately not too surprising.

The Fractional Quantum hall effect is the weirder one. As the name suggests it is similar in appearance to the integer quantum hall effect, the difference being that the plateaus occur at fractional (1/3 etc) values of the quantum of resistance, rather than at the integer levels. This is rather suprising however, as the explanation for the integer hall effect does not allow there to be fractional quanta. Another explanation, then, is needed. The effect only occurs at even thinner and purer sheets as well. One of the two effects requires a not too pure sheet, cannnot rememver which


The relevant point here is that in order for the explanation of the fractional quantum hall effect (and possibly the integer one as well?) to get of the ground, we /need/ to assume that the configuration space of the electrons in the sheet is two dimensional. For the explanation depends on the fact that the fundamental symmetry group of the particles is Bn, not Sn. Bn is the fundamental group of 2D space, and small 3D space does not equal 2D space. This is an important difference and makes this example much clearer than the Thermodynamic Limit, as this is cool.

** Breaking drops

In his 2005 paper Breaking Drops something something  cite:Batterman2005 argues that the breaking off of a droplet from a dripping faucet is an example of a genuine discontinuity in nature. While not mentioning the word "infinite idealization", it is clear that it was he is implying when making the argument.

The argument is flawed by using weird conceptions of continuity, in particular by taking the infinite limit before the end of the operation.

* Part III: Discussion(s)

(In this part I want to evaluate what I got out of my discussion of the case studies and generalize from there. These needn't be whole chapters, but it's useful for me to think of them as such for now. I also do not have much of anything I could add here, as I simply do not know exactly what I will conclude yet.)

* Bibliography
** Boundaries, vagueness, "denotation"

- cite:Varzi2015
- cite:Varzi2001
- cite:Sorensen1997
- cite:WEBER2010
- cite:Bueno2012
- cite:Weatherson2016
- cite:ungerProblemMany1980
- cite:Sanford1975
- cite:franklinArgumentsWhoseStrength2013c
- cite:Hacking1991

** (Infinite) Idealizations (theoretical, not applied to a particular problem)

- cite:Strevens2019
- cite:Strevens2007
- cite:Strevens2008
- cite:nortonInfiniteIdealizations2014
- cite:Norton2012
- cite:shechInfiniteIdealizationsPhysics2018a
- cite:Fletcher2019
- cite:Lutz
- cite:Knox2016
- cite:2016
- cite:Shapiro2004
- cite:Suarez2016
- cite:Shech2015b
- cite:Shech2013
- cite:Batterman2009
- cite:Batterman2001
- cite:Butterfield2011

** EIA

- cite:Shech2019a
- cite:Colyvan2006
- cite:Colyvan1998
- cite:Colyvan2019
- cite:Panza2016
- cite:Castro2013
- cite:Baron2016a

** Explanation

- cite:Woodward2019b
- cite:Wayne2011
- cite:salmonFourDecadesScientific2006a
- cite:Coffa1967
- cite:Bangu2015


  Overlaps much with the literature I gathered on idealization. I am still missing some good meta opininated meta literature on the subject, as I mentioned above

** Specific Effects and arguments surrounding them
*** Phase transitions [[id:4b10bcb4-8337-4b3e-be7a-adab788f995c][phase transitions]]

- cite:ech2013
- citeMenon2011
- citeKadanoff2009
- citeSklar1999
- citeCallender2001
- citeArdourel2018
- citeNorton2012

Overlaps much with the literature on infinite idealizations

*** FQHE [[id:8d8aa787-6796-410f-82d8-965c44698794][Fractional quantum hall effect (meta)]]

- citeShech2019a
- citeShech2015
- citeBain2016
- citesaundersExplanationQuantumStatistics
- citeTong2016
-

*** Aharonov Bohm Effect

- cite:Shech2018b
- cite: Tong2016
- cite:Earman2019
- cite:Dougherty2020

