#+title: open questions for my thesis
#+roam_tags: thesis
#+TODO: OPEN(o) | CLOSED (c)

* Context

Whilst working on my thesis I occasionally come across things I cannot quite seem to answer. I want to keep track of those here, and possibly incorporate these into my agenda/actionables through a shortcut.


* Questions
** OPEN Is localized vs extended a sensible dichotomy? :IQHE:
See [[file:20210302160720-impurities_turn_many_quantum_states_from_extended_to_localized.org][impurities turn many quantum states from extended to localized]]
/Asked On/ [2021-03-02 Tue 16:34]
** OPEN Why do [[file:20210302164341-extended_states_conduct_more_when_less_populated.org][extended states conduct more when less populated]] :IQHE:
/Asked On/ [2021-03-02 Tue 16:44]
** CLOSED Why iqhe so weird :IQHE:
/Asked On/ [2021-03-02 Tue 16:59]
** OPEN  [[file:20210309161743-is_the_neglection_of_electron_interactions_in_iqhe_justified.org][is the neglection of electron interactions in IQHE justified?]]
 [2021-03-09 Tue 16:20]
** CLOSED why is $R_i R_{i+1} R_i = R_{i+1} R_i R_{i+1}$ ?
 [2021-03-11 Thu 14:46]
** OPEN Is "the worldlines not getting entangled" not enough of an explanation for anyons? Do particles need to be 2D in order for there worldlines to get tangly?
 [2021-03-11 Thu 14:46]
** OPEN Do anyons /always/ occur at partially filled Landau levels?
 [2021-03-12 Fri 12:24]
** CLOSED [[file:20210312123438-where_does_the_hole_wf_come_from.org][where does the hole WF come from?]]
 [2021-03-12 Fri 12:34]
** OPEN How important is the fact that worldlines are unintertwinable to FQS arising?
 [2021-03-16 Tue 14:49]
** OPEN (difficult) How can a states go from unquantized to quantized under the influence of an magnetic field at all? This is the more fundamental difficulty
 [2021-03-17 Wed 12:00]
** OPEN Is the FQHE Toy Hamiltonian derived from the LWF or the other way around, like Ronnie suggested? The latter seems more plausible but I think it is actually the former
 [2021-03-19 Fri 10:05]
** CLOSED Why does being able to continuously connect the spacetime path to the situation where the paricles dont moce at all imply that the state is  "the same" as not rotating at all?
 [2021-03-22 Mon 14:56]
** CLOSED there seems to be an argument against my take on 3D fractional stats being possible. However, this relies on spin, which we are neglecting? Otherwise i think quasiholes have fractional spin anyway. https://en.wikipedia.org/wiki/Spin%E2%80%93statistics_theorem
 [2021-03-22 Mon 15:26]

* Unadressed issues

** OPEN Is "universality" something important? How do I deal with that "loss" of explanation?
