:PROPERTIES:
:ID:       26cf4180-c383-462c-8a35-2698bc11003a
:ROAM_REFS: cite:Strevens2019a
:mtime:    20210701200429
:ctime:    20210701200429
:END:
#+TITLE: Strevens2019a: The structure of asymptotic idealization
#+ROAM_KEY:#+filetags: idealization infinite_idealization reference
- tags ::
- keywords ::

* The structure of asymptotic idealization
  :PROPERTIES:
  :Custom_ID: Strevens2019a
  :URL:
  :AUTHOR: Strevens, M.
  :NOTER_DOCUMENT: /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf
  :NOTER_PAGE:
  :END:
*** “asymptotic explanations” (Batterman 2002). Such idealizations, he claims dramatically, though they rest on infinities that do not exist in the physical world, are essential for explaining certain physical behaviors; they do this by revealing emergent qualitative features of the situation that dominate the relevant actual physics and so “constrain and largely determine” what happens, or at least those aspects of what happens that are to be explained.
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::1++0.00;;annot-1-22]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-1-22
:mtime:    20210701200429
:ctime:    20210701200429
:END:
*** This essay attempts to make a contribution to the topic by posing the following question: is there any interesting difference between the rules that govern idealization in such canonical non-infinitary cases as frictionless planes and ideal gases, on the one hand, and Batterman’s asymptotic cases, on the other?
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::2++0.00;;annot-2-14]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-2-14
:mtime:    20210701200429
:ctime:    20210701200429
:END:
** 2 Simple idealization
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::2++0.00;;annot-2-15]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-2-15
:mtime:    20210701200429
:ctime:    20210701200429
:END:
*** These fictions [false representations in models] are called (at least when deliberate rather than inadvertent) idealizations.
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::2++0.00;;annot-2-16]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-2-16
:mtime:    20210929153908
:ctime:    20210929153908
:END:
*** This streamlining hints at one important function of idealization: it serves the prag- matic end of keeping calculations simple, either by making the mathematics more tractable or by reducing the empirical demands of the
:PROPERTIES:
:mtime:    20210701200429
:ctime:    20210701200429
:END:
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::3++0.00;;annot-3-31]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-3-31
:END:cite:Strevens2019a
*** in addition to simplification: idealizations call attention to factors that are explanatorily irrelevant to the target phenomenon
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::3++0.00;;annot-3-32]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-3-32
:mtime:    20210701200429
:ctime:    20210701200429
:END:
*** I will introduce asymptotic idealization by contrasting it with what I will call sim- ple idealization.
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::3++0.00;;annot-3-33]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-3-33
:mtime:    20210701200429
:ctime:    20210701200429
:END:
**** I say that a simple idealization notionally begins with a non-idealized model of the target phenomenon
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::3++0.00;;annot-3-34]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-3-34
:mtime:    20210701200429
:ctime:    20210701200429
:END:
**** Now an idealization is made—the veridical model is altered in some way that makes it no longer veridical. In a simple idealization, this is achieved by the straightforward operation of setting some parameter or parameters in the model to non-actual values, often zero.
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::3++0.00;;annot-3-35]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-3-35
:mtime:    20210701200429
:ctime:    20210701200429
:END:
**** . If the idealization is a valid one, the new model is, like the old veridical model, a good model of the target phenomenon
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::4++0.00;;annot-4-20]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-4-20
:mtime:    20210701200429
:ctime:    20210701200429
:END:
**** Further, the new model will do whatever idealized models are supposed to do: it will ease calculations, or it will effectively spotlight irrelevant factors.
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::4++0.00;;annot-4-21]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-4-21
:mtime:    20210701200429
:ctime:    20210701200429
:END:
**** The salient characteristic of a simple idealization, then, is that a simple operation, namely, a change in the parameters of the veridical model, creates a new, partly fictional model that continues to model and indeed to explain the target phenomenon.
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::4++0.00;;annot-4-22]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-4-22
:ctime:    20210929153908 20210701200429
:mtime:    20210929153908
:END:
*** In asymptotic idealization, by contrast, a fiction is introduced by taking some sort of limit.
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::4++0.00;;annot-4-23]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-4-23
:END:
**** a limit is taken as that parameter approaches zero. In some cases, taking a limit in this way is merely a roundabout path to a destination that can be more easily reached by simple idealization.
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::4++0.00;;annot-4-24]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-4-24
:mtime:    20210701200429
:ctime:    20210701200429
:END:
**** Asymptotic idealization is an interesting proposition, then, only in those cases where a simple substitution cannot be performed, which is to say only in those cases where a veridical model for mathematical reasons falls apart or otherwise behaves badly at the limiting value.
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::4++0.00;;annot-4-25]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-4-25
:mtime:    20210701200429
:ctime:    20210701200429
:END:
*** Norton (2012) has recently argued, however, that in these “interesting” cases, an asymptotically derived structure cannot be regarded as a genuine explanatory model of the system in question
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::4++0.00;;annot-4-26]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-4-26
:mtime:    20210701200429
:ctime:    20210701200429
:END:
*** To assess Norton’s argument, we need a more precise understanding of asymp- totic idealizing explanation.
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::4++0.00;;annot-4-27]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-4-27
:mtime:    20210701200429
:ctime:    20210701200429
:END:
*** to counter Norton and to affirm Batterman, showing that not all idealization is simple idealization.
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::4++0.00;;annot-4-28]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-4-28
:mtime:    20210701200429
:ctime:    20210701200429
:END:
** 3 Population genetics and determinism
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::5++0.00;;annot-5-20]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-5-20
:mtime:    20210701200429
:ctime:    20210701200429
:END:
*** In order to “idealize away” drift simply, what is wanted is a parameter in such a probability distribution that can be set to zero (or some other value) to obtain a deterministic process
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::6++0.00;;annot-6-21]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-6-21
:mtime:    20210701200429
:ctime:    20210701200429
:END:
*** But there is, in general, no such parameter. There is no sim- ple idealization, then, that transforms a more realistic, hence stochastic, population genetics model (let alone a veridical model) into a deterministic model.
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::6++0.00;;annot-6-22]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-6-22
:mtime:    20210701200429
:ctime:    20210701200429
:END:
*** One way forward is to build a deterministic model from scratch, and to rationalize the use of the model to explain by poinyinh out that its behavior closely tracks the behavior of the real system in the relevant aspects.
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::6++0.00;;annot-6-23]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-6-23
:ctime:    20210929153908 20210701200429
:mtime:    20210929153908
:END:
**** This strategy is what Norton calls “approximation”
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::6++0.00;;annot-6-24]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-6-24
:END:
*** An alternative strategy employed by some population geneticists is, by contrast, explicitly asymptotic
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::6++0.00;;annot-6-25]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-6-25
:mtime:    20210701200429
:ctime:    20210701200429
:END:
**** Deterministic models can be viewed as derived from more realistic models under the assumption that population size is infinite—since in an infinite population, there is no drift.
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::6++0.00;;annot-6-26]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-6-26
:mtime:    20210701200429
:ctime:    20210701200429
:END:
**** Drift cannot be set to zero directly, then, but it can zeroed indirectly by taking population size, another parameter in stochastic models, to be infinitely large.
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::6++0.00;;annot-6-27]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-6-27
:mtime:    20210701200429
:ctime:    20210701200429
:END:
*** That may sound like a simple idealization. As I will show you in the next section, however, it is not: the population size in a stochastic model cannot be set to infinity, not even by allowing the structure of the model to creep up to infinity by way of a lim- iting process.
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::6++0.00;;annot-6-28]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-6-28
:mtime:    20210701200429
:ctime:    20210701200429
:END:
**** Norton thinks this to be mistake
**** I will argue it is not by an alternative construal the infiitie population idealization, on whici i is well funded and has an important scientifitc role to play, especially in idealization.
** 4 Interpreting the infinite population idealization
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::7++0.00;;annot-7-19]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-7-19
:mtime:    20210701200429
:ctime:    20210701200429
:END:
*** when the population size becomes infinite, the structure over which the models assign probabilities disintegrates.
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::9++0.00;;annot-9-19]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-9-19
:ctime:    20210929153908 20210701200429
:mtime:    20210929153908
:END:
**** Relative frequencies (other than zero and one) are defined only for finite populations: if there are infinitely many As and infinitely many Bs, there is no determinate ratio of one to the other
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::9++0.00;;annot-9-20]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-9-20
:END:
*** In an infinite population, probability mathematicians therefore turn to limiting fre- quencies. But a limiting frequency is defined only relative to an ordering of outcomes
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::9++0.00;;annot-9-21]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-9-21
:ctime:    20210929153908 20210701200429
:mtime:    20210929153908
:END:
*** Consequently, the infinite population idealization cannot be treated as a simple idealization in which the population is set to infinity. How, then, to understand it? There are three options:
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::9++0.00;;annot-9-22]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-9-22
:END:
**** 1. It is an error. Biologists ought to renounce talk of infinite populations and find some other rationale for the use of deterministic models in population genetics.
**** 2. Biologists are tacitly building additional structure into population genetics models, enabling them to represent limiting frequencies and thus probability distributions over changes in limiting frequencies.
**** 3. The infinite population idealization is a successful idealization, but it is not a simple idealization.
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::9++0.00;;annot-9-23]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-9-23
:mtime:    20210701200429
:ctime:    20210701200429
:END:
**** Perhaps the least satisfying feature of this revisionary approach is its implication that no evolutionary events can be properly understood using a deterministic population genetics model—since such a construct is not itself a legitimate model of the system, but is rather only a mathematical heuristic to calculate what a certain legitimate model will predict.
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::10++0.00;;annot-10-26]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-10-26
:mtime:    20210701200429
:ctime:    20210701200429
:END:
*** The first two interpretations of the infinite population idealization, then, are inad- equate. If my reading is correct, then population geneticists such as Gillespie and Edwards treat deterministic models as genuine models that can be used (when cir- cumstances are right) to explain real events.
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::11++0.00;;annot-11-23]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-11-23
:mtime:    20210701200429
:ctime:    20210701200429
:END:
*** We must therefore embrace the third option presented above: the infinite population idealization is a genuine idealization, but not a simple idealization. It is an asymptotic idealization.
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::11++0.00;;annot-11-24]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-11-24
:mtime:    20210701200429
:ctime:    20210701200429
:END:
This doesn't follow at all, he needs to justify this way more, but I guess that's not what's important per se. He needs to justify either why we should take scientists' word on things or why it is a good explanation, both not easy.
** 5 Infinite populations as asymptotic extrapolations
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::11++0.00;;annot-11-25]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-11-25
:mtime:    20210701200429
:ctime:    20210701200429
:END:
*** Simple idealization is achieved by a simple act of parameter substitution: the scientist takes the veridical model and alters the value of one or more parameters.
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::11++0.00;;annot-11-26]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-11-26
:mtime:    20210701200429
:ctime:    20210701200429
:END:
*** Asymptotic idealization is achieved by a more complex process that I will call asymp- totic extrapolation.
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::12++0.00;;annot-12-20]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-12-20
:mtime:    20210701200429
:ctime:    20210701200429
:END:
**** First—of course—asymptotic extrapolation applied to a stochastic population genetics model should lead to a derministic model without being illogical.
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::12++0.00;;annot-12-21]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-12-21
:mtime:    20210701200429
:ctime:    20210701200429
:END:
**** Second, asymptotic extrapolation should go over and above simple idealization: it's not just simple idealization in disguise, as Norton things;
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::12++0.00;;annot-12-22]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-12-22
:mtime:    20210701200429
:ctime:    20210701200429
:END:
**** Third, asymptotic extrapolation should be to Batterman's liking (I like this one the least)
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::12++0.00;;annot-12-23]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-12-23
:mtime:    20210929153908
:ctime:    20210929153908
:END:
**** Fourth, the account of asymp- totic extrapolation ought to be compatible with just about any philosophical approach to explanation, idealization, or the nature of scientific models. (I dig this, we shouldn't favor a specific account of explanation)
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::12++0.00;;annot-12-24]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-12-24
:mtime:    20210701200429
:ctime:    20210701200429
:END:
**** And fifth, the operation should more or less capture the intuitive line of thought, associated with Fig. 1, that leads population geneticists to say that in infinite populations there is no drift. (so there is no option to say that what they're doing is wrong, how boring)
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::12++0.00;;annot-12-25]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-12-25
:mtime:    20210701200429
:ctime:    20210701200429
:END:
*** The question, then: in virtue of what ought we to regard such models as repre- senting the behavior of infinite populations? I propose a conventionalist answer: the assumption of infinitude is simply built in to the practice of asymptotic idealization.
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::15++0.00;;annot-15-21]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-15-21
:ctime:    20210929153908 20210701200429
:mtime:    20210929153908
:END:
*** Idealization, I suggest, is a rhetorical strategy to underline a fac- tor’s explanatory irrelevance.
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::15++0.00;;annot-15-22]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-15-22
:mtime:    20210929153908
:ctime:    20210929153908
:END:

*** Mere fiction is, however, not always sufficient to alert the scientific community to an idealization—the falsehood might, after all, be an inadvertent error. There is a certain conventional code, therefore, for indicating deliberate idealizations: where possible, set the parameter in question, or some appropriately related parameter, to zero or infinity.
:PROPERTIES:
:NOTER_PAGE: [[pdf:~/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf::16++0.00;;annot-16-14]]
:ID:       /home/thomas/OneDrive/HPS/Thesis/Papers/Thesis/General/Explanation_Idealization/Idealizations_Proper/StrevensM_2019_The_structure_of_asymptotic_idealization.pdf-annot-16-14
:END:



* Main point

Infinite idealizations are different from "simple" idealizations in the sense that there isn't a limiting case for the infinite idealization: something else changes by doing the limiting thing, discontinuity.


** He has a bad reason for dissuading the first 2 ways of understanding infinite, think more of why
** What is the main difference he posits between the infinite idealizations and simple ones?
*** Simple
"The salient characteristic of a simple idealization, then, is that a simple operation, namely, a change in the parameters of the veridical model, creates a new, partly fictional model that continues to model and indeed to explain the target phenomenon."

Indeed, as I thought, the change in the parameter creates a new, "easier" model which differs qualitatively (or relevantly) only in that that parameter is diffferent.

*** Asymptotic
"In asymptotic idealization, by contrast, a fiction is introduced by taking some sort of limit."
I mean, is that the relevant difference though? There are two concepts we should distinguish: the operation and the result. They differ in operation, but that is not what makes them interesting and I think is not what we should categorise idealization models on. What is interesting is the way in which these idealizations are used and what the accomplish. As Streven's says: "Asymptotic idealization is an interesting ppropoisiton only in those ases where a simple substitutiion cannot be performed" i.e. in those cases where the "veridical" or actual good super thorough model behaves badly in the limit. Indeed, we ought to look at this distinction like this, which is sort of the distinction cite:Norton2012 makes, see [[id:e5db852b-a680-4f56-8a2d-cba2f13aecb4][Idealization vs Approximation]]. HOwever, Norton also makes this distinction operationally, namely that to posit an idealization is to create a new model, while an approximation is simply to say something inexactly about a system.
Additionally, his characterization infinite idealizations mostly serve the purpose of explaining them away, so he also has two categories there: inf ids where the idealization matches and where they don't.

I propose that we only distinguish between the /result/ of the idealization operation: does it create a discontinuity or not? This is the relevant part of what we are discussing, and is where the trouble of idealizations lies as far as I am concerned. See [[id:0b697698-9e37-4bd7-a833-5580e878925e][idealizations should be distinguished by outcome, not by operation]]

*** Sum up

The relevant difference between asymptotic/infinite idealizations and simple ones, is that in infinite/asymptotic idealizations ANOTHER parameter is set to zero in order to affect a different one, while in simple idealizations the latter parameter is just set to zero immediately.

(Is this the same distinction I just made between continuous/discontinuous? Does affecting another parameter always lead to a discontinuity in that parameter? )

NO, this is not nexcessarily the same distinction, as this is one of operation rather than of result. I can imagine a model with some property X, which is a parameter of the model, and a more qualitative property Y, which is not a parameter of the model. Nevertheless, it could be that property X and Y are linearly dependent, and that taking a limit of X->0 leads to Y->0 smoothly.

What does make an important difference is that often times this qualitative property Y has a binary value, or at the very least a distinction between "zero" and "non-zero", where the latter could take on many different values.

Furthemore, another relevant case/part of it being considered a "difficult infinite idealization" is when Y might smoothly approach 0, but that X=0 or X=\infty is not a sensible model. I am not sure in what sense this matches my distinction. Furtermore, isn't it always the case that if X=0 or X=\infty the model doesn't make sense? It is already false, it seems kind of arbitrary to decide that for some models this means that the model doesn't exist and for others that it's just false but useful.

Although I do see that "an infinite sphere" is nothing, an infinite population does not per se not make sense, it's just too big to be considered "real". The question then is: what is the relevant distinction to make when deciding whether a specific infinite model "does not make sense"? I can only think of the sphere to be honest, as it is a contradiction in terms, but I could also see that the infinitely small/big model would contradict something we hold to be incontrovertible. However, this latter criterion is not as easily defined, as "being infitely big or zero" can be considered a contradiction already, as things in space can't be zero size or inifninte size.
** in his desiderata, does he assume that what scientists says is true? Even when he says that scientists rarely use explanation
** How important do I think difference making is?
** His goal is to sort of reproduce what is going on in the minds of scientists in a way to make sense.
I think htis is a good goal: ideally we would have a model of idealization that makes sense and also fits with what scientists do. However, the former should always go first, it should not be the case that what scientists do always make sense by definition.

* Thoughts

Strevens has towoo goals in this paper: delineate infiite idealizations (asymptotic idealizations as he caklls them) from "simple" idealizations, and explain how infinte idealizations, contra Norton, make sense.

The first he does rather well I think. His idea is somehwat like the following: simple idealizations simply set the value of a relevant parameter to some value like zero or infinity, and this transition to this value is smooth. Furthermore, the goal of setting this thing to zero is to just say that this paramater is not relevant in general for this model.

Inifinite idealizations on the other hand, set a value to zero or infinity but non smoothly affect other properties of the system in a relevant way. The goal of doing this then, is to set those properties in those relevant ways. So for population models, the goal is to get rid of the stochastic drift, but since there is no "stochastic drift" paramater, we need to tweak the only parameter we have, the size of the population. In contrast, when we set the friction to zero in a blokje on a slope, we do so intentionally to get rid of friction: we tweak the relevant paramater, and it does not matter if we simply set it or smoothly approach it in the limit. Consider on the other hand a model where "friction" is not a parameter we can change (not unrealistic as its not a fundamental force). Then, to get rid of friction, we might have to set the size of molecules to zero or whatever, which is not realistic but makes the friction zero, and we might then construct theories containing molecules of varying sizes and explain the success of our zero friction sliding block model by saying that the molecules are sufficiently small, or something.


** Streven's "asymptotic extrapolation" is (a form of?) abstraction
** The asymptotic extrapolation is just a way of calling Norton's "limit mismatch" justified

It has very similar characteristics. IS the extrapolation a "property" of the non-idealized models? I mean, they are idealized in a way.
Is "having a probability distribution of the form X" a property? I guess you can call quite a lot of things properties.

* Distinctions:

** Approximation (statement) vs Idealization (model)
** Simple idealization (setting parameter to zero) vs asymptotic idealization (setting another parameter to zero/infty to set another parameter to zero)
** Idealization (model) vs infinite idealization (subclass of model where a limiting operation is performed)
** Continuous operation vs discontinuous operation (idealizing operation which generates a discontinuity in some parameter)
** mismatch because of discontinuity vs mismatch of existence
** abstraction (generalization?) vs idealization (false model)

[[id:3c3b33a1-b8db-4be9-8acc-244cc7230172][Categorization of idealizations]]

